import type { QueryCard, Summary } from "@/lib/types";

// Opt-in demo data for screen-records (visit /dashboard?demo=1). NOT the live path — the
// real dashboard shows backend data only. Shows the full edge-case outcome range so the
// feed looks like a real clinic's morning, including the "while you slept" 2 AM booking.
const mins = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const DEMO_SUMMARY: Summary = {
  calls_today: 7,
  booked: 4,
  callback_needed: 1,
  missed: 0,
  avg_duration_s: 104,
};

export const DEMO_CARDS: QueryCard[] = [
  {
    call_session_id: "demo-1",
    direction: "inbound",
    phone_masked: "+91 ····· 4821",
    customer_name: "Priya Sharma",
    started_at: mins(11),
    summary: "Asked about a root canal and the earliest Saturday slot. Booked Sat 11:00 AM and confirmed by email.",
    outcome: "appointment_booked",
    confidence: 0.99,
    extracted: { service: "root canal", booked_for: "Sat 11:00 AM", booking_uid: "cal_8fk2" },
    duration_s: 132,
    has_recording: true,
    transcript: [
      { role: "agent", text: "Bright Smile Dental — automated assistant, the call may be recorded. How can I help?", ts: 0 },
      { role: "customer", text: "How much is a root canal, and do you have anything Saturday?", ts: 5 },
      { role: "agent", text: "Root canals start at ₹6,000. Saturday I have 11 AM or 2:30 PM — which suits you?", ts: 10 },
      { role: "customer", text: "11 works.", ts: 15 },
      { role: "agent", text: "Lovely. Your name and email? I'll read it back to be sure.", ts: 17 },
      { role: "customer", text: "Priya Sharma, priya.s@gmail.com.", ts: 22 },
      { role: "agent", text: "priya dot s at gmail dot com, Priya Sharma — correct?", ts: 27 },
      { role: "customer", text: "Yes.", ts: 30 },
      { role: "agent", text: "Booked you for Saturday 11 AM — confirmation's on its way. Anything else?", ts: 33 },
    ],
  },
  {
    call_session_id: "demo-2",
    direction: "inbound",
    phone_masked: "+91 ····· 9012",
    customer_name: "New patient",
    started_at: mins(214),
    summary: "Called at 2:14 AM about braces. Booked a consultation for Monday 5 PM.",
    outcome: "appointment_booked",
    confidence: 0.97,
    extracted: { service: "braces consult", booked_for: "Mon 5:00 PM", booking_uid: "cal_2p9z" },
    duration_s: 151,
    has_recording: true,
  },
  {
    call_session_id: "demo-3",
    direction: "inbound",
    phone_masked: "+91 ····· 5678",
    customer_name: "Rahul Verma",
    started_at: mins(38),
    summary: "Wanted Thursday evening — nothing open. Took a message for a callback tomorrow morning.",
    outcome: "callback_needed",
    confidence: 0.95,
    extracted: { callback_reason: "no_suitable_time", details: "wants Thursday evening", callback_window: "tomorrow AM" },
    duration_s: 74,
    has_recording: true,
  },
  {
    call_session_id: "demo-4",
    direction: "inbound",
    phone_masked: "+91 ····· 2233",
    customer_name: "Aisha Khan",
    started_at: mins(96),
    summary: "Asked about weekday opening hours. Answered: 9 AM–6 PM, Mon–Fri.",
    outcome: "question_answered",
    confidence: 0.92,
    extracted: { topic: "opening hours" },
    duration_s: 41,
    has_recording: true,
  },
  {
    call_session_id: "demo-5",
    direction: "outbound",
    phone_masked: "+91 ····· 7781",
    customer_name: "Vikram Rao",
    started_at: mins(132),
    summary: "Reminder call. Asked to be removed from the calling list — opted out.",
    outcome: "opt_out",
    confidence: 1.0,
    extracted: {},
    duration_s: 28,
    has_recording: true,
  },
  {
    call_session_id: "demo-6",
    direction: "inbound",
    phone_masked: "+91 ····· 3140",
    customer_name: "Unknown caller",
    started_at: mins(168),
    summary: "Caller couldn't verify the patient's identity. No details shared; ended politely.",
    outcome: "wrong_party",
    confidence: 0.9,
    extracted: {},
    duration_s: 36,
    has_recording: false,
  },
];
